### ISSUE TITLE
Can you please add Brisbane to the list of ResBaz 2019 sites?

### ISSUE THREAD

**Issue by weaverbel** [resbaz/resbaz2019#20]
Hi 

I wasn't sure how to add our Brisbane site to the general list for Resbaz 2019.

Can someone add us please, or tell me how to add us?

Thanks Belinda

**Comment by DamienIrving** [comment]
No problem, @weaverbel. Done :-)
https://github.com/resbaz/resbaz2019/commit/ea902940b69e810c02667bb50cd764a4e17284d1

**Comment by weaverbel** [comment]
Thanks. Bit of a labyrinth in there. But on the plus side I haven't broken
the template once this year :-)
