### ISSUE TITLE
Resbaz Tucson 2019

### ISSUE THREAD

**Issue by zoidy** [resbaz/resbaz2019#7]
Hello, this is a request to add ResBaz Tucson 2019 (May 20-22) to the map. The URL to the page is http://researchbazaar.arizona.edu/resbaz/resbazTucson2019/

Thanks!

**Comment by DamienIrving** [comment]
No problem, @zoidy. Good luck with the event!
https://github.com/resbaz/resbaz2019/commit/66e103c8a5efae268713608e7d7038f9e01d7adf
